using System;

namespace dgtk.OpenAL
{
    public enum ALC_ERROR :uint
	{
		ALC_NO_ERROR = ALCEnum.ALC_NO_ERROR,
		ALC_INVALID_DEVICE = ALCEnum.ALC_INVALID_DEVICE,
		ALC_INVALID_CONTEXT = ALCEnum.ALC_INVALID_CONTEXT,
		ALC_INVALID_ENUM = ALCEnum.ALC_INVALID_ENUM,
		ALC_INVALID_VALUE = ALCEnum.ALC_INVALID_VALUE,
		ALC_OUT_OF_MEMORY = ALCEnum.ALC_OUT_OF_MEMORY
	}	

    public enum AL_DistanceModel
    {
        AL_NONE = ALEnum.AL_NONE,
        AL_INVERSE_DISTANCE = ALEnum.AL_INVERSE_DISTANCE,
        AL_INVERSE_DISTANCE_CLAMPED = ALEnum.AL_INVERSE_DISTANCE_CLAMPED,
        AL_LINEAR_DISTANCE = ALEnum.AL_LINEAR_DISTANCE,
        AL_LINEAR_DISTANCE_CLAMPED = ALEnum.AL_LINEAR_DISTANCE_CLAMPED,
        AL_EXPONENT_DISTANCE = ALEnum.AL_EXPONENT_DISTANCE,
        AL_EXPONENT_DISTANCE_CLAMPED = ALEnum.AL_EXPONENT_DISTANCE_CLAMPED
    }
	
	public enum ALC_GetStringParam : uint
	{
		ALC_DEFAULT_DEVICE_SPECIFIER = ALCEnum.ALC_DEFAULT_DEVICE_SPECIFIER, 
		ALC_DEVICE_SPECIFIER = ALCEnum.ALC_DEVICE_SPECIFIER, 
		ALC_EXTENSIONS = ALCEnum.ALC_EXTENSIONS,
		ALC_CAPTURE_DEVICE_SPECIFIER = ALCEnum.ALC_CAPTURE_DEVICE_SPECIFIER,	
		ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER = ALCEnum.ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER, 
		ALC_DEFAULT_ALL_DEVICES_SPECIFIER = ALCEnum.ALC_DEFAULT_ALL_DEVICES_SPECIFIER,
		ALC_ALL_DEVICES_SPECIFIER = ALCEnum.ALC_ALL_DEVICES_SPECIFIER
	}
	
	public enum ALC_GetIntegerParam : uint
	{
		ALC_MAJOR_VERSION = ALCEnum.ALC_MAJOR_VERSION, 
		ALC_MINOR_VERSION = ALCEnum.ALC_MINOR_VERSION,  
		ALC_ATTRIBUTES_SIZE = ALCEnum.ALC_ATTRIBUTES_SIZE, 
		ALC_ALL_ATTRIBUTES = ALCEnum.ALC_ALL_ATTRIBUTES
	}
	
	public enum ALC_BufferFormat : int
	{
		AL_FORMAT_MONO8 = ALEnum.AL_FORMAT_MONO8, 
		AL_FORMAT_MONO16 = ALEnum.AL_FORMAT_MONO16, 
		AL_FORMAT_STEREO8 = ALEnum.AL_FORMAT_STEREO8, 
		AL_FORMAT_STEREO16 = ALEnum.AL_FORMAT_STEREO16,
        AL_FORMAT_MONO_MSADPCM_SOFT = ALEnum.AL_FORMAT_MONO_MSADPCM_SOFT,
        AL_FORMAT_STEREO_MSADPCM_SOFT = ALEnum.AL_FORMAT_STEREO_MSADPCM_SOFT,
        AL_FORMAT_BFORMAT2D_8 = ALEnum.AL_FORMAT_BFORMAT2D_8,
        AL_FORMAT_BFORMAT2D_16 = ALEnum.AL_FORMAT_BFORMAT2D_16,
        AL_FORMAT_BFORMAT2D_FLOAT32 = ALEnum.AL_FORMAT_BFORMAT2D_FLOAT32,
        AL_FORMAT_BFORMAT3D_8 = ALEnum.AL_FORMAT_BFORMAT3D_8,
        AL_FORMAT_BFORMAT3D_16 = ALEnum.AL_FORMAT_BFORMAT3D_16,
        AL_FORMAT_BFORMAT3D_FLOAT32 = ALEnum.AL_FORMAT_BFORMAT3D_FLOAT32,
        AL_FORMAT_BFORMAT2D_MULAW = ALEnum.AL_FORMAT_BFORMAT2D_MULAW,
        AL_FORMAT_BFORMAT3D_MULAW = ALEnum.AL_FORMAT_BFORMAT3D_MULAW,
        AL_FORMAT_IMA_ADPCM_MONO16_EXT = ALEnum.AL_FORMAT_IMA_ADPCM_MONO16_EXT,
        AL_FORMAT_IMA_ADPCM_STEREO16_EXT = ALEnum.AL_FORMAT_IMA_ADPCM_STEREO16_EXT,
        AL_FORMAT_WAVE_EXT = ALEnum.AL_FORMAT_WAVE_EXT,
        AL_FORMAT_VORBIS_EXT = ALEnum.AL_FORMAT_VORBIS_EXT,
        AL_FORMAT_QUAD8_LOKI = ALEnum.AL_FORMAT_QUAD8_LOKI,
        AL_FORMAT_QUAD16_LOKI = ALEnum.AL_FORMAT_QUAD16_LOKI,
        AL_FORMAT_MONO_FLOAT32 = ALEnum.AL_FORMAT_MONO_FLOAT32,
        AL_FORMAT_STEREO_FLOAT32 = ALEnum.AL_FORMAT_STEREO_FLOAT32,
        AL_FORMAT_MONO_DOUBLE_EXT = ALEnum.AL_FORMAT_MONO_DOUBLE_EXT,
        AL_FORMAT_STEREO_DOUBLE_EXT = ALEnum.AL_FORMAT_STEREO_DOUBLE_EXT,
        AL_FORMAT_MONO_MULAW_EXT = ALEnum.AL_FORMAT_MONO_MULAW_EXT,
        AL_FORMAT_STEREO_MULAW_EXT = ALEnum.AL_FORMAT_STEREO_MULAW_EXT,
        AL_FORMAT_MONO_ALAW_EXT = ALEnum.AL_FORMAT_MONO_ALAW_EXT,
        AL_FORMAT_STEREO_ALAW_EXT = ALEnum.AL_FORMAT_STEREO_ALAW_EXT,
        AL_FORMAT_QUAD8 = ALEnum.AL_FORMAT_QUAD8,
        AL_FORMAT_QUAD16 = ALEnum.AL_FORMAT_QUAD16,
        AL_FORMAT_QUAD32 = ALEnum.AL_FORMAT_QUAD32,
        AL_FORMAT_REAR8 = ALEnum.AL_FORMAT_REAR8,
        AL_FORMAT_REAR16 = ALEnum.AL_FORMAT_REAR16,
        AL_FORMAT_REAR32 = ALEnum.AL_FORMAT_REAR32,
        AL_FORMAT_51CHN8 = ALEnum.AL_FORMAT_51CHN8,
        AL_FORMAT_51CHN16 = ALEnum.AL_FORMAT_51CHN16,
        AL_FORMAT_51CHN32 = ALEnum.AL_FORMAT_51CHN32,
        AL_FORMAT_61CHN8 = ALEnum.AL_FORMAT_61CHN8,
        AL_FORMAT_61CHN16 = ALEnum.AL_FORMAT_61CHN16,
        AL_FORMAT_61CHN32 = ALEnum.AL_FORMAT_61CHN32,
        AL_FORMAT_71CHN8 = ALEnum.AL_FORMAT_71CHN8,
        AL_FORMAT_71CHN16 = ALEnum.AL_FORMAT_71CHN16,
        AL_FORMAT_71CHN32 = ALEnum.AL_FORMAT_71CHN32,
        AL_FORMAT_MONO_MULAW = ALEnum.AL_FORMAT_MONO_MULAW,
        AL_FORMAT_STEREO_MULAW = ALEnum.AL_FORMAT_STEREO_MULAW,
        AL_FORMAT_QUAD_MULAW = ALEnum.AL_FORMAT_QUAD_MULAW,
        AL_FORMAT_REAR_MULAW = ALEnum.AL_FORMAT_REAR_MULAW,
        AL_FORMAT_51CHN_MULAW = ALEnum.AL_FORMAT_51CHN_MULAW,
        AL_FORMAT_61CHN_MULAW = ALEnum.AL_FORMAT_61CHN_MULAW,
        AL_FORMAT_71CHN_MULAW = ALEnum.AL_FORMAT_71CHN_MULAW,
        AL_FORMAT_MONO_IMA4 = ALEnum.AL_FORMAT_MONO_IMA4,
        AL_FORMAT_STEREO_IMA4 = ALEnum.AL_FORMAT_STEREO_IMA4
    }

	public enum AL_FORMAT : int
	{
		AL_FORMAT_MONO8 = ALEnum.AL_FORMAT_MONO8, 
		AL_FORMAT_MONO16 = ALEnum.AL_FORMAT_MONO16, 
		AL_FORMAT_STEREO8 = ALEnum.AL_FORMAT_STEREO8, 
		AL_FORMAT_STEREO16 = ALEnum.AL_FORMAT_STEREO16,
        AL_FORMAT_MONO_MSADPCM_SOFT = ALEnum.AL_FORMAT_MONO_MSADPCM_SOFT,
        AL_FORMAT_STEREO_MSADPCM_SOFT = ALEnum.AL_FORMAT_STEREO_MSADPCM_SOFT,
        AL_FORMAT_BFORMAT2D_8 = ALEnum.AL_FORMAT_BFORMAT2D_8,
        AL_FORMAT_BFORMAT2D_16 = ALEnum.AL_FORMAT_BFORMAT2D_16,
        AL_FORMAT_BFORMAT2D_FLOAT32 = ALEnum.AL_FORMAT_BFORMAT2D_FLOAT32,
        AL_FORMAT_BFORMAT3D_8 = ALEnum.AL_FORMAT_BFORMAT3D_8,
        AL_FORMAT_BFORMAT3D_16 = ALEnum.AL_FORMAT_BFORMAT3D_16,
        AL_FORMAT_BFORMAT3D_FLOAT32 = ALEnum.AL_FORMAT_BFORMAT3D_FLOAT32,
        AL_FORMAT_BFORMAT2D_MULAW = ALEnum.AL_FORMAT_BFORMAT2D_MULAW,
        AL_FORMAT_BFORMAT3D_MULAW = ALEnum.AL_FORMAT_BFORMAT3D_MULAW,
        AL_FORMAT_IMA_ADPCM_MONO16_EXT = ALEnum.AL_FORMAT_IMA_ADPCM_MONO16_EXT,
        AL_FORMAT_IMA_ADPCM_STEREO16_EXT = ALEnum.AL_FORMAT_IMA_ADPCM_STEREO16_EXT,
        AL_FORMAT_WAVE_EXT = ALEnum.AL_FORMAT_WAVE_EXT,
        AL_FORMAT_VORBIS_EXT = ALEnum.AL_FORMAT_VORBIS_EXT,
        AL_FORMAT_QUAD8_LOKI = ALEnum.AL_FORMAT_QUAD8_LOKI,
        AL_FORMAT_QUAD16_LOKI = ALEnum.AL_FORMAT_QUAD16_LOKI,
        AL_FORMAT_MONO_FLOAT32 = ALEnum.AL_FORMAT_MONO_FLOAT32,
        AL_FORMAT_STEREO_FLOAT32 = ALEnum.AL_FORMAT_STEREO_FLOAT32,
        AL_FORMAT_MONO_DOUBLE_EXT = ALEnum.AL_FORMAT_MONO_DOUBLE_EXT,
        AL_FORMAT_STEREO_DOUBLE_EXT = ALEnum.AL_FORMAT_STEREO_DOUBLE_EXT,
        AL_FORMAT_MONO_MULAW_EXT = ALEnum.AL_FORMAT_MONO_MULAW_EXT,
        AL_FORMAT_STEREO_MULAW_EXT = ALEnum.AL_FORMAT_STEREO_MULAW_EXT,
        AL_FORMAT_MONO_ALAW_EXT = ALEnum.AL_FORMAT_MONO_ALAW_EXT,
        AL_FORMAT_STEREO_ALAW_EXT = ALEnum.AL_FORMAT_STEREO_ALAW_EXT,
        AL_FORMAT_QUAD8 = ALEnum.AL_FORMAT_QUAD8,
        AL_FORMAT_QUAD16 = ALEnum.AL_FORMAT_QUAD16,
        AL_FORMAT_QUAD32 = ALEnum.AL_FORMAT_QUAD32,
        AL_FORMAT_REAR8 = ALEnum.AL_FORMAT_REAR8,
        AL_FORMAT_REAR16 = ALEnum.AL_FORMAT_REAR16,
        AL_FORMAT_REAR32 = ALEnum.AL_FORMAT_REAR32,
        AL_FORMAT_51CHN8 = ALEnum.AL_FORMAT_51CHN8,
        AL_FORMAT_51CHN16 = ALEnum.AL_FORMAT_51CHN16,
        AL_FORMAT_51CHN32 = ALEnum.AL_FORMAT_51CHN32,
        AL_FORMAT_61CHN8 = ALEnum.AL_FORMAT_61CHN8,
        AL_FORMAT_61CHN16 = ALEnum.AL_FORMAT_61CHN16,
        AL_FORMAT_61CHN32 = ALEnum.AL_FORMAT_61CHN32,
        AL_FORMAT_71CHN8 = ALEnum.AL_FORMAT_71CHN8,
        AL_FORMAT_71CHN16 = ALEnum.AL_FORMAT_71CHN16,
        AL_FORMAT_71CHN32 = ALEnum.AL_FORMAT_71CHN32,
        AL_FORMAT_MONO_MULAW = ALEnum.AL_FORMAT_MONO_MULAW,
        AL_FORMAT_STEREO_MULAW = ALEnum.AL_FORMAT_STEREO_MULAW,
        AL_FORMAT_QUAD_MULAW = ALEnum.AL_FORMAT_QUAD_MULAW,
        AL_FORMAT_REAR_MULAW = ALEnum.AL_FORMAT_REAR_MULAW,
        AL_FORMAT_51CHN_MULAW = ALEnum.AL_FORMAT_51CHN_MULAW,
        AL_FORMAT_61CHN_MULAW = ALEnum.AL_FORMAT_61CHN_MULAW,
        AL_FORMAT_71CHN_MULAW = ALEnum.AL_FORMAT_71CHN_MULAW,
        AL_FORMAT_MONO_IMA4 = ALEnum.AL_FORMAT_MONO_IMA4,
        AL_FORMAT_STEREO_IMA4 = ALEnum.AL_FORMAT_STEREO_IMA4
	}

	public enum AL_BufferParam : int
	{
		AL_FREQUENCY = ALEnum.AL_FREQUENCY, 
		AL_BITS = ALEnum.AL_BITS, 
		AL_CHANNELS = ALEnum.AL_CHANNELS,  
		AL_SIZE = ALEnum.AL_SIZE, 
		//AL_DATA
	}
	
	public enum AL_SourcefParam : int
	{
		AL_PITCH = ALEnum.AL_PITCH, 
		AL_GAIN = ALEnum.AL_GAIN, 
		AL_MIN_GAIN = ALEnum.AL_MIN_GAIN, 
		AL_MAX_GAIN = ALEnum.AL_MAX_GAIN, 
		AL_MAX_DISTANCE = ALEnum.AL_MAX_DISTANCE, 
		AL_ROLLOFF_FACTOR = ALEnum.AL_ROLLOFF_FACTOR, 
		AL_CONE_OUTER_GAIN = ALEnum.AL_CONE_OUTER_GAIN, 
		AL_CONE_INNER_ANGLE = ALEnum.AL_CONE_INNER_ANGLE, 
		AL_CONE_OUTER_ANGLE = ALEnum.AL_CONE_OUTER_ANGLE, 
		AL_REFERENCE_DISTANCE = ALEnum.AL_REFERENCE_DISTANCE,
		AL_SEC_OFFSET = ALEnum.AL_SEC_OFFSET,
        AL_AIR_ABSORPTION_FACTOR = ALEnum.AL_AIR_ABSORPTION_FACTOR,
        AL_ROOM_ROLLOFF_FACTOR = ALEnum.AL_ROOM_ROLLOFF_FACTOR,
        AL_CONE_OUTER_GAINHF = ALEnum.AL_CONE_OUTER_GAINHF
	}
	
	public enum AL_Source3Param : int
	{
		AL_POSITION = ALEnum.AL_POSITION, 
		AL_VELOCITY = ALEnum.AL_VELOCITY, 
		AL_DIRECTION = ALEnum.AL_DIRECTION,
        AL_AUXILIARY_SEND_FILTER = ALEnum.AL_AUXILIARY_SEND_FILTER
	}
	
	public enum AL_SourceiParam : int
	{
		AL_SOURCE_RELATIVE = ALEnum.AL_SOURCE_RELATIVE, 
		AL_CONE_INNER_ANGLE = ALEnum.AL_CONE_INNER_ANGLE, 
		AL_CONE_OUTER_ANGLE = ALEnum.AL_CONE_OUTER_ANGLE, 
		AL_SOURCE_TYPE = ALEnum.AL_SOURCE_TYPE,
        AL_LOOPING = ALEnum.AL_LOOPING,
		AL_BUFFER = ALEnum.AL_BUFFER, 
		AL_SOURCE_STATE = ALEnum.AL_SOURCE_STATE,
        AL_DIRECT_FILTER = ALEnum.AL_DIRECT_FILTER,
        AL_AUXILIARY_SEND_FILTER = ALEnum.AL_AUXILIARY_SEND_FILTER,
        AL_SEC_OFFSET = ALEnum.AL_SEC_OFFSET,
        AL_SAMPLE_OFFSET = ALEnum.AL_SAMPLE_OFFSET,
        AL_BYTE_OFFSET = ALEnum.AL_BYTE_OFFSET,
	}
	
	public enum AL_SourcebParam : int
	{
		AL_LOOPING = ALEnum.AL_LOOPING, 
        AL_DIRECT_FILTER_GAINHF_AUTO = ALEnum.AL_DIRECT_FILTER_GAINHF_AUTO,
        AL_AUXILIARY_SEND_FILTER_GAIN_AUTO = ALEnum.AL_AUXILIARY_SEND_FILTER_GAIN_AUTO,
        AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO = ALEnum.AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO
	}
	
	public enum AL_GetSourceiParam : int
	{
		AL_SOURCE_RELATIVE = ALEnum.AL_SOURCE_RELATIVE, 
		AL_BUFFER = ALEnum.AL_BUFFER,  
		AL_SOURCE_TYPE = ALEnum.AL_SOURCE_TYPE, 
        AL_LOOPING = ALEnum.AL_LOOPING, 
		AL_SOURCE_STATE = ALEnum.AL_SOURCE_STATE,
		AL_BUFFERS_QUEUED = ALEnum.AL_BUFFERS_QUEUED, 
		AL_BUFFERS_PROCESSED = ALEnum.AL_BUFFERS_PROCESSED,
        AL_SEC_OFFSET = ALEnum.AL_SEC_OFFSET,
        AL_SAMPLE_OFFSET = ALEnum.AL_SAMPLE_OFFSET,
        AL_BYTE_OFFSET = ALEnum.AL_BYTE_OFFSET,
	}
	
	public enum AL_ListenerifParam : int
	{
		AL_GAIN = ALEnum.AL_GAIN,
        AL_METERS_PER_UNIT = ALEnum.AL_METERS_PER_UNIT
	}
	
	public enum AL_Listener3vParam : int
	{
		AL_POSITION = ALEnum.AL_POSITION, 
		AL_VELOCITY = ALEnum.AL_VELOCITY, 
		AL_ORIENTATION = ALEnum.AL_ORIENTATION
	}
	
	public enum AL_GetParam : int
	{
		AL_DOPPLER_FACTOR = ALEnum.AL_DOPPLER_FACTOR, 
		AL_SPEED_OF_SOUND = ALEnum.AL_SPEED_OF_SOUND, 
		AL_DISTANCE_MODEL = ALEnum.AL_DISTANCE_MODEL
	}
	
	public enum AL_GetStringParam : int
	{
		AL_VENDOR = ALEnum.AL_VENDOR,  
		AL_VERSION = ALEnum.AL_VERSION, 
		AL_RENDERER = ALEnum.AL_RENDERER, 
		AL_EXTENSIONS = ALEnum.AL_EXTENSIONS
	}
	
	public enum AL_ERROR : int
	{
		AL_INVALID = ALEnum.AL_INVALID,
		AL_NO_ERROR = ALEnum.AL_NO_ERROR, 
		AL_INVALID_NAME = ALEnum.AL_INVALID_NAME, 
		AL_INVALID_ENUM = ALEnum.AL_INVALID_ENUM, 
		AL_INVALID_VALUE = ALEnum.AL_INVALID_VALUE, 
		AL_INVALID_OPERATION = ALEnum.AL_INVALID_OPERATION, 
		AL_OUT_OF_MEMORY = ALEnum.AL_OUT_OF_MEMORY
	}
	
	public enum AL_SourceState : uint
	{
		AL_INITIAL = ALEnum.AL_INITIAL,
		AL_PLAYING = ALEnum.AL_PLAYING,
		AL_PAUSED = ALEnum.AL_PAUSED,
		AL_STOPPED = ALEnum.AL_STOPPED
	}
	
	public enum AL_SourceType : uint
	{
		AL_STATIC = ALEnum.AL_STATIC,
		AL_STREAMING = ALEnum.AL_STREAMING,
		AL_UNDETERMINED = ALEnum.AL_UNDETERMINED,
	}

    // EXT:

    public enum AL_AuxiliaryEffectSlot
    {
        AL_EFFECTSLOT_EFFECT = 0x0001,
        AL_EFFECTSLOT_GAIN = 0x0002,
        AL_EFFECTSLOT_AUXILIARY_SEND_AUTO = 0x0003
    }

    public enum AL_EffectParam
    {
        AL_REVERB_DENSITY = 0x0001,
        AL_REVERB_DIFFUSION = 0x0002,
        AL_REVERB_GAIN = 0x0003,
        AL_REVERB_GAINHF = 0x0004,
        AL_REVERB_DECAY_TIME = 0x0005,
        AL_REVERB_DECAY_HFRATIO = 0x0006,
        AL_REVERB_REFLECTIONS_GAIN = 0x0007,
        AL_REVERB_REFLECTIONS_DELAY = 0x0008,
        AL_REVERB_LATE_REVERB_GAIN = 0x0009,
        AL_REVERB_LATE_REVERB_DELAY = 0x000A,
        AL_REVERB_AIR_ABSORPTION_GAINHF = 0x000B,
        AL_REVERB_ROOM_ROLLOFF_FACTOR = 0x000C,
        AL_REVERB_DECAY_HFLIMIT = 0x000D,
        AL_CHORUS_WAVEFORM = 0x0001,
        AL_CHORUS_PHASE = 0x0002,
        AL_CHORUS_RATE =  0x0003,
        AL_CHORUS_DEPTH = 0x0004,
        AL_CHORUS_FEEDBACK = 0x0005,
        AL_CHORUS_DELAY = 0x0006,
        AL_DISTORTION_EDGE = 0x0001,
        AL_DISTORTION_GAIN = 0x0002,
        AL_DISTORTION_LOWPASS_CUTOFF = 0x0003,
        AL_DISTORTION_EQCENTER = 0x0004,
        AL_DISTORTION_EQBANDWIDTH = 0x0005,
        AL_ECHO_DELAY =   0x0001,
        AL_ECHO_LRDELAY = 0x0002,
        AL_ECHO_DAMPING = 0x0003,
        AL_ECHO_FEEDBACK =   0x0004,
        AL_ECHO_SPREAD =  0x0005,
        AL_FLANGER_WAVEFORM = 0x0001,
        AL_FLANGER_PHASE =   0x0002,
        AL_FLANGER_RATE = 0x0003,
        AL_FLANGER_DEPTH =   0x0004,
        AL_FLANGER_FEEDBACK = 0x0005,
        AL_FLANGER_DELAY =   0x0006,
        AL_FREQUENCY_SHIFTER_FREQUENCY = 0x0001,
        AL_FREQUENCY_SHIFTER_LEFT_DIRECTION = 0x0002,
        AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION = 0x0003,
        AL_VOCAL_MORPHER_PHONEMEA = 0x0001,
        AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING = 0x0002,
        AL_VOCAL_MORPHER_PHONEMEB = 0x0003,
        AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING = 0x0004,
        AL_VOCAL_MORPHER_WAVEFORM = 0x0005,
        AL_VOCAL_MORPHER_RATE = 0x0006,
        AL_PITCH_SHIFTER_COARSE_TUNE = 0x0001,
        AL_PITCH_SHIFTER_FINE_TUNE = 0x0002,
        AL_RING_MODULATOR_FREQUENCY = 0x0001,
        AL_RING_MODULATOR_HIGHPASS_CUTOFF = 0x0002,
        AL_RING_MODULATOR_WAVEFORM = 0x0003,
        AL_AUTOWAH_ATTACK_TIME = 0x0001,
        AL_AUTOWAH_RELEASE_TIME = 0x0002,
        AL_AUTOWAH_RESONANCE = 0x0003,
        AL_AUTOWAH_PEAK_GAIN = 0x0004,
        AL_COMPRESSOR_ONOFF = 0x0001,
        AL_EQUALIZER_LOW_GAIN = 0x0001,
        AL_EQUALIZER_LOW_CUTOFF = 0x0002,
        AL_EQUALIZER_MID1_GAIN = 0x0003,
        AL_EQUALIZER_MID1_CENTER = 0x0004,
        AL_EQUALIZER_MID1_WIDTH = 0x0005,
        AL_EQUALIZER_MID2_GAIN = 0x0006,
        AL_EQUALIZER_MID2_CENTER = 0x0007,
        AL_EQUALIZER_MID2_WIDTH = 0x0008,
        AL_EQUALIZER_HIGH_GAIN = 0x0009,
        AL_EQUALIZER_HIGH_CUTOFF = 0x000A,
        AL_EFFECT_FIRST_PARAMETER = 0x0000,
        AL_EFFECT_LAST_PARAMETER = 0x8000,
        AL_EFFECT_TYPE = 0x8001
    }

    public enum AL_Effect_Type
    {
        AL_EFFECT_NULL = 0x0000,
        AL_EFFECT_REVERB = 0x0001,
        AL_EFFECT_CHORUS = 0x0002,
        AL_EFFECT_DISTORTION = 0x0003,
        AL_EFFECT_ECHO = 0x0004,
        AL_EFFECT_FLANGER = 0x0005,
        AL_EFFECT_FREQUENCY_SHIFTER = 0x0006,
        AL_EFFECT_VOCAL_MORPHER = 0x0007,
        AL_EFFECT_PITCH_SHIFTER = 0x0008,
        AL_EFFECT_RING_MODULATOR = 0x0009,
        AL_EFFECT_AUTOWAH = 0x000A,
        AL_EFFECT_COMPRESSOR = 0x000B,
        AL_EFFECT_EQUALIZER = 0x000C,
    }

    public enum AL_FilterPassParam
    {
        AL_LOWPASS_GAIN = 0x0001,
        AL_LOWPASS_GAINHF = 0x0002,
        AL_HIGHPASS_GAIN = 0x0001,
        AL_HIGHPASS_GAINLF = 0x0002,
        AL_BANDPASS_GAIN = 0x0001,
        AL_BANDPASS_GAINLF = 0x0002,
        AL_BANDPASS_GAINHF = 0x0003
    }

    public enum AL_FilterParam
    {
        AL_FILTER_FIRST_PARAMETER = 0x0000,
        AL_FILTER_LAST_PARAMETER = 0x8000,
        AL_FILTER_TYPE = 0x8001
    }

    public enum AL_Filter_Type
    {
        AL_FILTER_NULL = 0x0000,
        AL_FILTER_LOWPASS = 0x0001,
        AL_FILTER_HIGHPASS = 0x0002,
        AL_FILTER_BANDPASS = 0x0003
    }

    public enum AL_Vocal_Morpher_Param
    {
        AL_VOCAL_MORPHER_MIN_PHONEMEA = 0,
        AL_VOCAL_MORPHER_MAX_PHONEMEA = 29,
        AL_VOCAL_MORPHER_DEFAULT_PHONEMEA = 0,

        AL_VOCAL_MORPHER_MIN_PHONEMEA_COARSE_TUNING = (-24),
        AL_VOCAL_MORPHER_MAX_PHONEMEA_COARSE_TUNING = 24,
        AL_VOCAL_MORPHER_DEFAULT_PHONEMEA_COARSE_TUNING = 0,

        AL_VOCAL_MORPHER_MIN_PHONEMEB = 0,
        AL_VOCAL_MORPHER_MAX_PHONEMEB = 29,
        AL_VOCAL_MORPHER_DEFAULT_PHONEMEB = 10,

        AL_VOCAL_MORPHER_PHONEME_A = 0,
        AL_VOCAL_MORPHER_PHONEME_E = 1,
        AL_VOCAL_MORPHER_PHONEME_I = 2,
        AL_VOCAL_MORPHER_PHONEME_O = 3,
        AL_VOCAL_MORPHER_PHONEME_U = 4,
        AL_VOCAL_MORPHER_PHONEME_AA = 5,
        AL_VOCAL_MORPHER_PHONEME_AE = 6,
        AL_VOCAL_MORPHER_PHONEME_AH = 7,
        AL_VOCAL_MORPHER_PHONEME_AO = 8,
        AL_VOCAL_MORPHER_PHONEME_EH = 9,
        AL_VOCAL_MORPHER_PHONEME_ER = 10,
        AL_VOCAL_MORPHER_PHONEME_IH = 11,
        AL_VOCAL_MORPHER_PHONEME_IY = 12,
        AL_VOCAL_MORPHER_PHONEME_UH = 13,
        AL_VOCAL_MORPHER_PHONEME_UW = 14,
        AL_VOCAL_MORPHER_PHONEME_B = 15,
        AL_VOCAL_MORPHER_PHONEME_D = 16,
        AL_VOCAL_MORPHER_PHONEME_F = 17,
        AL_VOCAL_MORPHER_PHONEME_G = 18,
        AL_VOCAL_MORPHER_PHONEME_J = 19,
        AL_VOCAL_MORPHER_PHONEME_K = 20,
        AL_VOCAL_MORPHER_PHONEME_L = 21,
        AL_VOCAL_MORPHER_PHONEME_M = 22,
        AL_VOCAL_MORPHER_PHONEME_N = 23,
        AL_VOCAL_MORPHER_PHONEME_P = 24,
        AL_VOCAL_MORPHER_PHONEME_R = 25,
        AL_VOCAL_MORPHER_PHONEME_S = 26,
        AL_VOCAL_MORPHER_PHONEME_T = 27,
        AL_VOCAL_MORPHER_PHONEME_V = 28,
        AL_VOCAL_MORPHER_PHONEME_Z = 29,

        AL_VOCAL_MORPHER_MIN_PHONEMEB_COARSE_TUNING = (-24),
        AL_VOCAL_MORPHER_MAX_PHONEMEB_COARSE_TUNING = 24,
        AL_VOCAL_MORPHER_DEFAULT_PHONEMEB_COARSE_TUNING = 0,

        AL_VOCAL_MORPHER_MIN_WAVEFORM = 0,
        AL_VOCAL_MORPHER_MAX_WAVEFORM = 2,
        AL_VOCAL_MORPHER_DEFAULT_WAVEFORM =  0,

        AL_VOCAL_MORPHER_WAVEFORM_SINUSOID = 0,
        AL_VOCAL_MORPHER_WAVEFORM_TRIANGLE = 1,
        AL_VOCAL_MORPHER_WAVEFORM_SAWTOOTH = 2,

    }

    public enum ALEnum : int
    {
        AL_INVALID = -1,
        AL_NONE = 0,
        AL_FALSE = 0,
        AL_TRUE = 1,
        AL_SOURCE_RELATIVE = 0x202,
        AL_CONE_INNER_ANGLE = 0x1001,
        AL_CONE_OUTER_ANGLE = 0x1002,
        AL_PITCH = 0x1003,        
        AL_POSITION = 0x1004,        
        AL_DIRECTION = 0x1005,        
        AL_VELOCITY = 0x1006,
        AL_LOOPING = 0x1007,
        AL_BUFFER = 0x1009,        
        AL_GAIN = 0x100A,
        AL_MIN_GAIN = 0x100D,
        AL_MAX_GAIN = 0x100E,
        AL_ORIENTATION = 0x100F,
        AL_CHANNEL_MASK = 0x3000,
        AL_SOURCE_STATE = 0x1010,
        AL_INITIAL = 0x1011,
        AL_PLAYING = 0x1012,
        AL_PAUSED = 0x1013,
        AL_STOPPED = 0x1014,
        AL_BUFFERS_QUEUED = 0x1015,
        AL_BUFFERS_PROCESSED = 0x1016,
        AL_SEC_OFFSET = 0x1024,
        AL_SAMPLE_OFFSET = 0x1025,
        AL_BYTE_OFFSET = 0x1026,
        AL_SOURCE_TYPE = 0x1027,
        AL_STATIC = 0x1028,
        AL_STREAMING = 0x1029,
        AL_UNDETERMINED = 0x1030,
        AL_FORMAT_MONO8 = 0x1100,
        AL_FORMAT_MONO16 = 0x1101,
        AL_FORMAT_STEREO8 = 0x1102,
        AL_FORMAT_STEREO16 = 0x1103,
        AL_REFERENCE_DISTANCE = 0x1020,
        AL_ROLLOFF_FACTOR = 0x1021,
        AL_CONE_OUTER_GAIN = 0x1022,
        AL_MAX_DISTANCE = 0x1023,
        AL_FREQUENCY = 0x2001,
        AL_BITS = 0x2002,
        AL_CHANNELS = 0x2003,
        AL_SIZE = 0x2004,
        AL_UNUSED = 0x2010,
        AL_PENDING = 0x2011,
        AL_PROCESSED = 0x2012,
        AL_NO_ERROR = AL_FALSE,
        AL_INVALID_NAME = 0xA001,
        AL_ILLEGAL_ENUM = 0xA002,
        AL_INVALID_ENUM = 0xA002,
        AL_INVALID_VALUE = 0xA003,
        AL_ILLEGAL_COMMAND = 0xA004,
        AL_INVALID_OPERATION = 0xA004,
        AL_OUT_OF_MEMORY = 0xA005,
        AL_VENDOR = 0xB001,
        AL_VERSION = 0xB002,
        AL_RENDERER = 0xB003,
        AL_EXTENSIONS = 0xB004,
        AL_DOPPLER_FACTOR = 0xC000,
        AL_DOPPLER_VELOCITY = 0xC001,
        AL_SPEED_OF_SOUND = 0xC003,
        AL_DISTANCE_MODEL = 0xD000,
        AL_INVERSE_DISTANCE = 0xD001,
        AL_INVERSE_DISTANCE_CLAMPED = 0xD002,
        AL_LINEAR_DISTANCE = 0xD003,
        AL_LINEAR_DISTANCE_CLAMPED = 0xD004,
        AL_EXPONENT_DISTANCE = 0xD005,
        AL_EXPONENT_DISTANCE_CLAMPED = 0xD006,      

        // Extensions:
        ALC_EFX_MAJOR_VERSION = 0x20001,
        ALC_EFX_MINOR_VERSION = 0x20002,
        ALC_MAX_AUXILIARY_SENDS = 0x20003,
        AL_METERS_PER_UNIT = 0x20004,
        AL_DIRECT_FILTER = 0x20005,
        AL_AUXILIARY_SEND_FILTER = 0x20006,
        AL_AIR_ABSORPTION_FACTOR = 0x20007,
        AL_ROOM_ROLLOFF_FACTOR = 0x20008,
        AL_CONE_OUTER_GAINHF = 0x20009,
        AL_DIRECT_FILTER_GAINHF_AUTO = 0x2000A,
        AL_AUXILIARY_SEND_FILTER_GAIN_AUTO = 0x2000B,
        AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO = 0x2000C,
        AL_REVERB_DENSITY = 0x0001,
        AL_REVERB_DIFFUSION = 0x0002,
        AL_REVERB_GAIN = 0x0003,
        AL_REVERB_GAINHF = 0x0004,
        AL_REVERB_DECAY_TIME = 0x0005,
        AL_REVERB_DECAY_HFRATIO = 0x0006,
        AL_REVERB_REFLECTIONS_GAIN = 0x0007,
        AL_REVERB_REFLECTIONS_DELAY = 0x0008,
        AL_REVERB_LATE_REVERB_GAIN = 0x0009,
        AL_REVERB_LATE_REVERB_DELAY = 0x000A,
        AL_REVERB_AIR_ABSORPTION_GAINHF = 0x000B,
        AL_REVERB_ROOM_ROLLOFF_FACTOR = 0x000C,
        AL_REVERB_DECAY_HFLIMIT = 0x000D,
        AL_CHORUS_WAVEFORM = 0x0001,
    	AL_CHORUS_PHASE = 0x0002,
        AL_CHORUS_RATE = 0x0003,
        AL_CHORUS_DEPTH = 0x0004,
        AL_CHORUS_FEEDBACK = 0x0005,
        AL_CHORUS_DELAY = 0x0006,
        AL_DISTORTION_EDGE = 0x0001,
        AL_DISTORTION_GAIN = 0x0002,
        AL_DISTORTION_LOWPASS_CUTOFF = 0x0003,
        AL_DISTORTION_EQCENTER = 0x0004,
        AL_DISTORTION_EQBANDWIDTH = 0x0005,
        AL_ECHO_DELAY = 0x0001,
        AL_ECHO_LRDELAY = 0x0002,
        AL_ECHO_DAMPING = 0x0003,
        AL_ECHO_FEEDBACK = 0x0004,
        AL_ECHO_SPREAD = 0x0005,
        AL_FLANGER_WAVEFORM = 0x0001,
        AL_FLANGER_PHASE = 0x0002,
        AL_FLANGER_RATE = 0x0003,
        AL_FLANGER_DEPTH = 0x0004,
        AL_FLANGER_FEEDBACK = 0x0005,
        AL_FLANGER_DELAY = 0x0006,
        AL_FREQUENCY_SHIFTER_FREQUENCY = 0x0001,
        AL_FREQUENCY_SHIFTER_LEFT_DIRECTION = 0x0002,
        AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION = 0x0003,
        AL_VOCAL_MORPHER_PHONEMEA = 0x0001,
        AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING = 0x0002,
        AL_VOCAL_MORPHER_PHONEMEB = 0x0003,
        AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING = 0x0004,
        AL_VOCAL_MORPHER_WAVEFORM = 0x0005,
        AL_VOCAL_MORPHER_RATE = 0x0006,
        AL_PITCH_SHIFTER_COARSE_TUNE = 0x0001,
        AL_PITCH_SHIFTER_FINE_TUNE = 0x0002,
        AL_RING_MODULATOR_FREQUENCY = 0x0001,
        AL_RING_MODULATOR_HIGHPASS_CUTOFF = 0x0002,
        AL_RING_MODULATOR_WAVEFORM = 0x0003,
        AL_AUTOWAH_ATTACK_TIME = 0x0001,
        AL_AUTOWAH_RELEASE_TIME = 0x0002,
        AL_AUTOWAH_RESONANCE = 0x0003,
        AL_AUTOWAH_PEAK_GAIN = 0x0004,
        AL_COMPRESSOR_ONOFF = 0x0001,
        AL_EQUALIZER_LOW_GAIN = 0x0001,
        AL_EQUALIZER_LOW_CUTOFF = 0x0002,
        AL_EQUALIZER_MID1_GAIN = 0x0003,
        AL_EQUALIZER_MID1_CENTER = 0x0004,
        AL_EQUALIZER_MID1_WIDTH = 0x0005,
        AL_EQUALIZER_MID2_GAIN = 0x0006,
        AL_EQUALIZER_MID2_CENTER = 0x0007,
        AL_EQUALIZER_MID2_WIDTH = 0x0008,
        AL_EQUALIZER_HIGH_GAIN = 0x0009,
        AL_EQUALIZER_HIGH_CUTOFF = 0x000A,
        AL_EFFECT_FIRST_PARAMETER = 0x0000,
        AL_EFFECT_LAST_PARAMETER = 0x8000,
        AL_EFFECT_TYPE = 0x8001,
        AL_EFFECT_NULL = 0x0000, 
        AL_EFFECT_REVERB = 0x0001,
        AL_EFFECT_CHORUS = 0x0002,
        AL_EFFECT_DISTORTION = 0x0003,
        AL_EFFECT_ECHO = 0x0004,
        AL_EFFECT_FLANGER = 0x0005,
        AL_EFFECT_FREQUENCY_SHIFTER = 0x0006,
        AL_EFFECT_VOCAL_MORPHER = 0x0007,
        AL_EFFECT_PITCH_SHIFTER = 0x0008,
        AL_EFFECT_RING_MODULATOR = 0x0009,
        AL_EFFECT_AUTOWAH = 0x000A,
        AL_EFFECT_COMPRESSOR = 0x000B,
        AL_EFFECT_EQUALIZER = 0x000C,
        AL_EFFECTSLOT_EFFECT = 0x0001,
        AL_EFFECTSLOT_GAIN = 0x0002,
        AL_EFFECTSLOT_AUXILIARY_SEND_AUTO = 0x0003,
        AL_EFFECTSLOT_NULL = 0x0000,
        AL_LOWPASS_GAIN = 0x0001,
        AL_LOWPASS_GAINHF = 0x0002,
        AL_HIGHPASS_GAIN = 0x0001,
        AL_HIGHPASS_GAINLF = 0x0002,
        AL_BANDPASS_GAIN = 0x0001,
        AL_BANDPASS_GAINLF = 0x0002,
        AL_BANDPASS_GAINHF = 0x0003,
        AL_FILTER_FIRST_PARAMETER = 0x0000,
        AL_FILTER_LAST_PARAMETER = 0x8000,
        AL_FILTER_TYPE = 0x8001,
        AL_FILTER_NULL = 0x0000,  
        AL_FILTER_LOWPASS = 0x0001,
        AL_FILTER_HIGHPASS = 0x0002,
        AL_FILTER_BANDPASS = 0x0003,

        #region EXT

        //AL_LOKI_IMA_ADPCM_format:
        AL_FORMAT_IMA_ADPCM_MONO16_EXT =  0x10000,
        AL_FORMAT_IMA_ADPCM_STEREO16_EXT = 0x10001,
        //AL_LOKI_WAVE_format:
        AL_FORMAT_WAVE_EXT = 0x10002,
        //AL_EXT_vorbis:
        AL_FORMAT_VORBIS_EXT = 0x10003,
        //AL_LOKI_quadriphonic:
        AL_FORMAT_QUAD8_LOKI = 0x10004,
        AL_FORMAT_QUAD16_LOKI = 0x10005,
        //AL_EXT_float32:
        AL_FORMAT_MONO_FLOAT32 = 0x10010,
        AL_FORMAT_STEREO_FLOAT32 = 0x10011,
        //AL_EXT_double:
        AL_FORMAT_MONO_DOUBLE_EXT = 0x10012,
        AL_FORMAT_STEREO_DOUBLE_EXT = 0x10013,
        //AL_EXT_MULAW:
        AL_FORMAT_MONO_MULAW_EXT = 0x10014,
        AL_FORMAT_STEREO_MULAW_EXT = 0x10015,
        //AL_EXT_ALAW:
        AL_FORMAT_MONO_ALAW_EXT = 0x10016,
        AL_FORMAT_STEREO_ALAW_EXT = 0x10017,
        //AL_EXT_MCFORMATS:
        AL_FORMAT_QUAD8 = 0x1204,
        AL_FORMAT_QUAD16 = 0x1205,
        AL_FORMAT_QUAD32 = 0x1206,
        AL_FORMAT_REAR8 = 0x1207,
        AL_FORMAT_REAR16 = 0x1208,
        AL_FORMAT_REAR32 = 0x1209,
        AL_FORMAT_51CHN8 = 0x120A,
        AL_FORMAT_51CHN16 = 0x120B,
        AL_FORMAT_51CHN32 = 0x120C,
        AL_FORMAT_61CHN8 = 0x120D,
        AL_FORMAT_61CHN16 = 0x120E,
        AL_FORMAT_61CHN32 = 0x120F,
        AL_FORMAT_71CHN8 = 0x1210,
        AL_FORMAT_71CHN16 = 0x1211,
        AL_FORMAT_71CHN32 = 0x1212,
        //AL_EXT_MULAW_MCFORMATS:
        AL_FORMAT_MONO_MULAW = 0x10014,
        AL_FORMAT_STEREO_MULAW = 0x10015,
        AL_FORMAT_QUAD_MULAW = 0x10021,
        AL_FORMAT_REAR_MULAW = 0x10022,
        AL_FORMAT_51CHN_MULAW = 0x10023,
        AL_FORMAT_61CHN_MULAW = 0x10024,
        AL_FORMAT_71CHN_MULAW = 0x10025,
        //AL_EXT_IMA4:
        AL_FORMAT_MONO_IMA4 = 0x1300,
        AL_FORMAT_STEREO_IMA4 = 0x1301,
        //ALC_EXT_disconnect:
        ALC_CONNECTED = 0x313,
        //AL_EXT_source_distance_model:
        AL_SOURCE_DISTANCE_MODEL = 0x200,
        //AL_SOFT_buffer_sub_data:
        AL_BYTE_RW_OFFSETS_SOFT = 0x1031,
        AL_SAMPLE_RW_OFFSETS_SOFT = 0x1032,
        //AL_SOFT_loop_points:
        AL_LOOP_POINTS_SOFT = 0x2015,
        //AL_EXT_FOLDBACK:
        AL_FOLDBACK_EVENT_BLOCK = 0x4112,
        AL_FOLDBACK_EVENT_START = 0x4111,
        AL_FOLDBACK_EVENT_STOP = 0x4113,
        AL_FOLDBACK_MODE_MONO = 0x4101,
        AL_FOLDBACK_MODE_STEREO = 0x4102,
        //ALC_EXT_DEDICATED:
        AL_DEDICATED_GAIN = 0x0001,
        AL_EFFECT_DEDICATED_DIALOGUE = 0x9001,
        AL_EFFECT_DEDICATED_LOW_FREQUENCY_EFFECT = 0x9000,
        //AL_SOFT_buffer_samples:
        AL_MONO_SOFT = 0x1500,
        AL_STEREO_SOFT =  0x1501,
        AL_REAR_SOFT = 0x1502,
        AL_QUAD_SOFT = 0x1503,
        AL_5POINT1_SOFT = 0x1504,
        AL_6POINT1_SOFT = 0x1505,
        AL_7POINT1_SOFT = 0x1506,

        AL_BYTE_SOFT = 0x1400,
        AL_UNSIGNED_BYTE_SOFT = 0x1401,
        AL_SHORT_SOFT = 0x1402,
        AL_UNSIGNED_SHORT_SOFT = 0x1403,
        AL_INT_SOFT = 0x1404,
        AL_UNSIGNED_INT_SOFT = 0x1405,
        AL_FLOAT_SOFT = 0x1406,
        AL_DOUBLE_SOFT = 0x1407,
        AL_BYTE3_SOFT = 0x1408,
        AL_UNSIGNED_BYTE3_SOFT = 0x1409,

        AL_INTERNAL_FORMAT_SOFT = 0x2008,
        AL_BYTE_LENGTH_SOFT = 0x2009,
        AL_SAMPLE_LENGTH_SOFT = 0x200A,
        AL_SEC_LENGTH_SOFT = 0x200B,

        //AL_SOFT_direct_channels:
        AL_DIRECT_CHANNELS_SOFT = 0x1033,

        //AL_EXT_STEREO_ANGLES:
        AL_STEREO_ANGLES = 0x1030,

        //AL_EXT_SOURCE_RADIUS:
        AL_SOURCE_RADIUS = 0x1031,

        //AL_SOFT_source_latency:
        AL_SAMPLE_OFFSET_LATENCY_SOFT = 0x1200,
        AL_SEC_OFFSET_LATENCY_SOFT = 0x1201,

        //AL_SOFT_deferred_updates:
        AL_DEFERRED_UPDATES_SOFT = 0xC002,

        //AL_SOFT_block_alignment:
        AL_UNPACK_BLOCK_ALIGNMENT_SOFT = 0x200C,
        AL_PACK_BLOCK_ALIGNMENT_SOFT = 0x200D,

        //AL_SOFT_MSADPCM:
        AL_FORMAT_MONO_MSADPCM_SOFT = 0x1302,
        AL_FORMAT_STEREO_MSADPCM_SOFT = 0x1303,

        //AL_EXT_BFORMAT:
        AL_FORMAT_BFORMAT2D_8 = 0x20021,
        AL_FORMAT_BFORMAT2D_16 = 0x20022,
        AL_FORMAT_BFORMAT2D_FLOAT32 = 0x20023,
        AL_FORMAT_BFORMAT3D_8 = 0x20031,
        AL_FORMAT_BFORMAT3D_16 = 0x20032,
        AL_FORMAT_BFORMAT3D_FLOAT32 = 0x20033,

        //AL_EXT_MULAW_BFORMAT:
        AL_FORMAT_BFORMAT2D_MULAW = 0x10031,
        AL_FORMAT_BFORMAT3D_MULAW = 0x10032,

        //AL_SOFT_gain_clamp_ex:
        AL_GAIN_LIMIT_SOFT = 0x200E,

        //AL_SOFT_source_resampler:
        AL_NUM_RESAMPLERS_SOFT = 0x1210,
        AL_DEFAULT_RESAMPLER_SOFT = 0x1211,
        AL_SOURCE_RESAMPLER_SOFT = 0x1212,
        AL_RESAMPLER_NAME_SOFT = 0x1213,

        //AL_SOFT_source_spatialize:
        AL_SOURCE_SPATIALIZE_SOFT = 0x1214,
        AL_AUTO_SOFT = 0x0002,

        //ALC_SOFT_output_limiter:
        ALC_OUTPUT_LIMITER_SOFT = 0x199A,

        //ALC_SOFT_device_clock:
        ALC_DEVICE_CLOCK_SOFT = 0x1600,
        ALC_DEVICE_LATENCY_SOFT = 0x1601,
        ALC_DEVICE_CLOCK_LATENCY_SOFT = 0x1602,
        AL_SAMPLE_OFFSET_CLOCK_SOFT = 0x1202,
        AL_SEC_OFFSET_CLOCK_SOFT = 0x1203,

        //AL_SOFT_direct_channels_remix:
        AL_DROP_UNMATCHED_SOFT = 0x0001,
        AL_REMIX_UNMATCHED_SOFT = 0x0002,

        //AL_SOFT_bformat_ex:
        AL_AMBISONIC_LAYOUT_SOFT = 0x1997,
        AL_AMBISONIC_SCALING_SOFT = 0x1998,

        AL_FUMA_SOFT = 0x0000,
        AL_ACN_SOFT = 0x0001,

        AL_SN3D_SOFT = 0x0001,
        AL_N3D_SOFT = 0x0002,

        ALC_AMBISONIC_LAYOUT_SOFT = 0x1997,
        ALC_AMBISONIC_SCALING_SOFT = 0x1998,
        ALC_AMBISONIC_ORDER_SOFT = 0x1999,
        ALC_MAX_AMBISONIC_ORDER_SOFT = 0x199B,

        ALC_BFORMAT3D_SOFT = 0x1507,

        ALC_FUMA_SOFT = 0x0000,
        ALC_ACN_SOFT = 0x0001,

        ALC_SN3D_SOFT = 0x0001,
        ALC_N3D_SOFT = 0x0002,

        //AL_SOFT_effect_target:
        AL_EFFECTSLOT_TARGET_SOFT = 0x199C,

        //AL_SOFT_events:
        AL_EVENT_CALLBACK_FUNCTION_SOFT = 0x19A2,
        AL_EVENT_CALLBACK_USER_PARAM_SOFT = 0x19A3,
        AL_EVENT_TYPE_BUFFER_COMPLETED_SOFT = 0x19A4,
        AL_EVENT_TYPE_SOURCE_STATE_CHANGED_SOFT = 0x19A5,
        AL_EVENT_TYPE_DISCONNECTED_SOFT = 0x19A6,

        #endregion
    }

    public enum ALCEnum : uint
    {
        ALC_FALSE = 0,
        ALC_TRUE = 1,
        ALC_FREQUENCY = 0x1007,
        ALC_REFRESH = 0x1008,
        ALC_SYNC = 0x1009,
        ALC_MONO_SOURCES = 0x1010,
        ALC_STEREO_SOURCES = 0x1011,
        ALC_NO_ERROR = ALC_FALSE,
        ALC_INVALID_DEVICE = 0xA001,
        ALC_INVALID_CONTEXT = 0xA002,
        ALC_INVALID_ENUM = 0xA003,
        ALC_INVALID_VALUE = 0xA004,
        ALC_OUT_OF_MEMORY = 0xA005,
        ALC_DEFAULT_DEVICE_SPECIFIER = 0x1004,
        ALC_DEVICE_SPECIFIER = 0x1005,
        ALC_EXTENSIONS = 0x1006,
        ALC_MAJOR_VERSION = 0x1000,
        ALC_MINOR_VERSION = 0x1001,
        ALC_ATTRIBUTES_SIZE = 0x1002,
        ALC_ALL_ATTRIBUTES = 0x1003,
        ALC_DEFAULT_ALL_DEVICES_SPECIFIER = 0x1012,
        ALC_ALL_DEVICES_SPECIFIER = 0x1013,
        ALC_CAPTURE_DEVICE_SPECIFIER = 0x310,
        ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER = 0x311,
        ALC_CAPTURE_SAMPLES = 0x312,

        #region EXT

        //ALC_LOKI_audio_channel:
        ALC_CHAN_MAIN_LOKI = 0x500001,
        ALC_CHAN_PCM_LOKI = 0x500002,
        ALC_CHAN_CD_LOKI = 0x500003,

        //ALC_SOFT_loopback:
        ALC_FORMAT_CHANNELS_SOFT = 0x1990,
        ALC_FORMAT_TYPE_SOFT = 0x1991,

        ALC_BYTE_SOFT = 0x1400,
        ALC_UNSIGNED_BYTE_SOFT = 0x1401,
        ALC_SHORT_SOFT = 0x1402,
        ALC_UNSIGNED_SHORT_SOFT = 0x1403,
        ALC_INT_SOFT = 0x1404,
        ALC_UNSIGNED_INT_SOFT = 0x1405,
        ALC_FLOAT_SOFT =  0x1406,

        ALC_MONO_SOFT =   0x1500,
        ALC_STEREO_SOFT = 0x1501,
        ALC_QUAD_SOFT = 0x1503,
        ALC_5POINT1_SOFT = 0x1504,
        ALC_6POINT1_SOFT = 0x1505,
        ALC_7POINT1_SOFT = 0x1506,

        //ALC_EXT_DEFAULT_FILTER_ORDER:
        ALC_DEFAULT_FILTER_ORDER = 0x1100,

        //ALC_SOFT_HRTF:
        ALC_HRTF_SOFT = 0x1992,
        ALC_DONT_CARE_SOFT = 0x0002,
        ALC_HRTF_STATUS_SOFT = 0x1993,
        ALC_HRTF_DISABLED_SOFT = 0x0000,
        ALC_HRTF_ENABLED_SOFT = 0x0001,
        ALC_HRTF_DENIED_SOFT = 0x0002,
        ALC_HRTF_REQUIRED_SOFT = 0x0003,
        ALC_HRTF_HEADPHONES_DETECTED_SOFT = 0x0004,
        ALC_HRTF_UNSUPPORTED_FORMAT_SOFT = 0x0005,
        ALC_NUM_HRTF_SPECIFIERS_SOFT = 0x1994,
        ALC_HRTF_SPECIFIER_SOFT = 0x1995,
        ALC_HRTF_ID_SOFT = 0x1996

        #endregion
    }
}